version: "3"
services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./react-app:/app"
    depends_on:
      - node-api

  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./node-api:/app"
